In [4]:
import pandas as pd
import numpy as np
from scipy import stats
import seaborn as sn
import matplotlib.pyplot as plt

In [5]:
from google.colab import files
uploaded = files.upload()

Saving data_clean.csv to data_clean (1).csv


In [6]:
data = pd.read_csv("data_clean.csv", index_col=0)

In [7]:
data

Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
1     41.0    190.0   7.4     67     5    1  2010    67       S
2     36.0    118.0   8.0     72     5    2  2010    72       C
3     12.0    149.0  12.6     74     5    3  2010    74      PS
4     18.0    313.0  11.5     62     5    4  2010    62       S
5      NaN      NaN  14.3     56     5    5  2010    56       S
..     ...      ...   ...    ...   ...  ...   ...   ...     ...
154   41.0    190.0   7.4     67     5    1  2010    67       C
155   30.0    193.0   6.9     70     9   26  2010    70      PS
156    NaN    145.0  13.2     77     9   27  2010    77       S
157   14.0    191.0  14.3     75     9   28  2010    75       S
158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 9 columns]

In [8]:
#Data Structure
print(type(data))
print(data.shape)

<class 'pandas.core.frame.DataFrame'>
(158, 9)


In [9]:
data.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Temp C      object
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [10]:
data.describe()

Ozone     Solar.R        Wind         Day    Year        Temp
count  120.000000  151.000000  158.000000  158.000000   158.0  158.000000
mean    41.583333  185.403974    9.957595   16.006329  2010.0   77.727848
std     32.620709   88.723103    3.511261    8.997166     0.0    9.377877
min      1.000000    7.000000    1.700000    1.000000  2010.0   56.000000
25%     18.000000  119.000000    7.400000    8.000000  2010.0   72.000000
50%     30.500000  197.000000    9.700000   16.000000  2010.0   78.500000
75%     61.500000  257.000000   11.875000   24.000000  2010.0   84.000000
max    168.000000  334.000000   20.700000   31.000000  2010.0   97.000000

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158 entries, 1 to 158
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Ozone    120 non-null    float64
 1   Solar.R  151 non-null    float64
 2   Wind     158 non-null    float64
 3   Temp C   158 non-null    object 
 4   Month    158 non-null    object 
 5   Day      158 non-null    int64  
 6   Year     158 non-null    int64  
 7   Temp     158 non-null    int64  
 8   Weather  155 non-null    object 
dtypes: float64(3), int64(3), object(3)
memory usage: 12.3+ KB


Data Type Conversion

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158 entries, 1 to 158
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Ozone    120 non-null    float64
 1   Solar.R  151 non-null    float64
 2   Wind     158 non-null    float64
 3   Temp C   158 non-null    object 
 4   Month    158 non-null    object 
 5   Day      158 non-null    int64  
 6   Year     158 non-null    int64  
 7   Temp     158 non-null    int64  
 8   Weather  155 non-null    object 
dtypes: float64(3), int64(3), object(3)
memory usage: 12.3+ KB


In [13]:
data['Month']=pd.to_numeric(data['Month'],errors='coerce') #[1,1.5,NAN] january NA
data['Temp C']=pd.to_numeric(data['Temp C'],errors='coerce')# coerce will introduce NA values for non numeric data in the columns
data['Weather']=data['Weather'].astype('category')           #data['Wind']=data['Wind'].astype('int64')

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 158 entries, 1 to 158
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype   
---  ------   --------------  -----   
 0   Ozone    120 non-null    float64 
 1   Solar.R  151 non-null    float64 
 2   Wind     158 non-null    float64 
 3   Temp C   157 non-null    float64 
 4   Month    157 non-null    float64 
 5   Day      158 non-null    int64   
 6   Year     158 non-null    int64   
 7   Temp     158 non-null    int64   
 8   Weather  155 non-null    category
dtypes: category(1), float64(5), int64(3)
memory usage: 11.4 KB


Duplicates

In [15]:
data.duplicated()

1      False
2      False
3      False
4      False
5      False
       ...  
154    False
155    False
156    False
157     True
158    False
Length: 158, dtype: bool

In [16]:
data[data.duplicated()].shape

(1, 9)

In [17]:
#Print the duplicated rows
data[data.duplicated()]

Ozone  Solar.R  Wind  Temp C  Month  Day  Year  Temp Weather
157   14.0    191.0  14.3    75.0    9.0   28  2010    75       S

In [18]:
data_cleaned1 = data.drop_duplicates()

In [19]:
data_cleaned1.shape

(157, 9)

Drop Columns

In [20]:
data

Ozone  Solar.R  Wind  Temp C  Month  Day  Year  Temp Weather
1     41.0    190.0   7.4    67.0    5.0    1  2010    67       S
2     36.0    118.0   8.0    72.0    5.0    2  2010    72       C
3     12.0    149.0  12.6    74.0    5.0    3  2010    74      PS
4     18.0    313.0  11.5    62.0    5.0    4  2010    62       S
5      NaN      NaN  14.3    56.0    5.0    5  2010    56       S
..     ...      ...   ...     ...    ...  ...   ...   ...     ...
154   41.0    190.0   7.4    67.0    5.0    1  2010    67       C
155   30.0    193.0   6.9    70.0    9.0   26  2010    70      PS
156    NaN    145.0  13.2    77.0    9.0   27  2010    77       S
157   14.0    191.0  14.3    75.0    9.0   28  2010    75       S
158   18.0    131.0   8.0    76.0    9.0   29  2010    76       C

[158 rows x 9 columns]

In [21]:
data_cleaned2 = data_cleaned1.drop('Temp C', axis=1)

In [22]:
data_cleaned2

Ozone  Solar.R  Wind  Month  Day  Year  Temp Weather
1     41.0    190.0   7.4    5.0    1  2010    67       S
2     36.0    118.0   8.0    5.0    2  2010    72       C
3     12.0    149.0  12.6    5.0    3  2010    74      PS
4     18.0    313.0  11.5    5.0    4  2010    62       S
5      NaN      NaN  14.3    5.0    5  2010    56       S
..     ...      ...   ...    ...  ...   ...   ...     ...
153   20.0    223.0  11.5    9.0   30  2010    68       S
154   41.0    190.0   7.4    5.0    1  2010    67       C
155   30.0    193.0   6.9    9.0   26  2010    70      PS
156    NaN    145.0  13.2    9.0   27  2010    77       S
158   18.0    131.0   8.0    9.0   29  2010    76       C

[157 rows x 8 columns]

Rename the columns

In [23]:
#Rename the Solar column
data_cleaned3 = data_cleaned2.rename({'Solar.R': 'Solar'}, axis=1)

In [24]:
data_cleaned3

Ozone  Solar  Wind  Month  Day  Year  Temp Weather
1     41.0  190.0   7.4    5.0    1  2010    67       S
2     36.0  118.0   8.0    5.0    2  2010    72       C
3     12.0  149.0  12.6    5.0    3  2010    74      PS
4     18.0  313.0  11.5    5.0    4  2010    62       S
5      NaN    NaN  14.3    5.0    5  2010    56       S
..     ...    ...   ...    ...  ...   ...   ...     ...
153   20.0  223.0  11.5    9.0   30  2010    68       S
154   41.0  190.0   7.4    5.0    1  2010    67       C
155   30.0  193.0   6.9    9.0   26  2010    70      PS
156    NaN  145.0  13.2    9.0   27  2010    77       S
158   18.0  131.0   8.0    9.0   29  2010    76       C

[157 rows x 8 columns]

Missing Values and Imputation

In [25]:
import seaborn as sns
cols = data_cleaned3.columns
colours = ['#000099', '#ffff00']
sns.heatmap(data_cleaned3[cols].isnull(),
            cmap=sns.color_palette(colours))

In [26]:
data_cleaned3[data_cleaned3.isnull().any(axis=1)].head()

Ozone  Solar  Wind  Month  Day  Year  Temp Weather
5     NaN    NaN  14.3    5.0    5  2010    56       S
6    28.0    NaN  14.9    5.0    6  2010    66       C
10    NaN  194.0   8.6    5.0   10  2010    69       S
11    7.0    NaN   6.9    5.0   11  2010    74       C
24   32.0   92.0  12.0    NaN   24  2010    61       C

In [27]:
data_cleaned3.isnull().sum()

Ozone      38
Solar       7
Wind        0
Month       1
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [28]:
data_cleaned3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 157 entries, 1 to 158
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype   
---  ------   --------------  -----   
 0   Ozone    119 non-null    float64 
 1   Solar    150 non-null    float64 
 2   Wind     157 non-null    float64 
 3   Month    156 non-null    float64 
 4   Day      157 non-null    int64   
 5   Year     157 non-null    int64   
 6   Temp     157 non-null    int64   
 7   Weather  154 non-null    category
dtypes: category(1), float64(4), int64(3)
memory usage: 10.1 KB


In [29]:
# Mean Imputations
mean = data_cleaned3['Ozone'].mean()
print(mean)

41.81512605042017


In [30]:
data_cleaned3['Ozone'] = data_cleaned3['Ozone'].fillna(mean)

In [31]:
data_cleaned3

Ozone  Solar  Wind  Month  Day  Year  Temp Weather
1    41.000000  190.0   7.4    5.0    1  2010    67       S
2    36.000000  118.0   8.0    5.0    2  2010    72       C
3    12.000000  149.0  12.6    5.0    3  2010    74      PS
4    18.000000  313.0  11.5    5.0    4  2010    62       S
5    41.815126    NaN  14.3    5.0    5  2010    56       S
..         ...    ...   ...    ...  ...   ...   ...     ...
153  20.000000  223.0  11.5    9.0   30  2010    68       S
154  41.000000  190.0   7.4    5.0    1  2010    67       C
155  30.000000  193.0   6.9    9.0   26  2010    70      PS
156  41.815126  145.0  13.2    9.0   27  2010    77       S
158  18.000000  131.0   8.0    9.0   29  2010    76       C

[157 rows x 8 columns]

In [32]:
#Missing value imputation for categorical value
#Get the object columns
obj_columns = data_cleaned3[['Weather']]

In [33]:
obj_columns.isnull().sum()

Weather    3
dtype: int64

In [34]:
#Missing value imputation for categorical value
#df.mode
#df.median
obj_columns = obj_columns.fillna(obj_columns.mode().iloc[0])

In [35]:
obj_columns.isnull().sum()
data.boxplot()

/usr/local/lib/python3.8/dist-packages/matplotlib/cbook/__init__.py:1376: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X = np.atleast_1d(X.T if isinstance(X, np.ndarray) else np.asarray(X))


In [36]:
data_cleaned3

Ozone  Solar  Wind  Month  Day  Year  Temp Weather
1    41.000000  190.0   7.4    5.0    1  2010    67       S
2    36.000000  118.0   8.0    5.0    2  2010    72       C
3    12.000000  149.0  12.6    5.0    3  2010    74      PS
4    18.000000  313.0  11.5    5.0    4  2010    62       S
5    41.815126    NaN  14.3    5.0    5  2010    56       S
..         ...    ...   ...    ...  ...   ...   ...     ...
153  20.000000  223.0  11.5    9.0   30  2010    68       S
154  41.000000  190.0   7.4    5.0    1  2010    67       C
155  30.000000  193.0   6.9    9.0   26  2010    70      PS
156  41.815126  145.0  13.2    9.0   27  2010    77       S
158  18.000000  131.0   8.0    9.0   29  2010    76       C

[157 rows x 8 columns]

In [37]:
obj_columns.shape

(157, 1)

In [38]:
data_cleaned4 = data_cleaned3.drop(['Weather'],axis=1,inplace=True)

In [39]:
#Join the dataset with imputed object dataset
data_cleaned4 = pd.concat([data_cleaned3,obj_columns],axis=1)

In [40]:
data_cleaned4.isnull().sum()

Ozone      0
Solar      7
Wind       0
Month      1
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [41]:
data_cleaned4

Ozone  Solar  Wind  Month  Day  Year  Temp Weather
1    41.000000  190.0   7.4    5.0    1  2010    67       S
2    36.000000  118.0   8.0    5.0    2  2010    72       C
3    12.000000  149.0  12.6    5.0    3  2010    74      PS
4    18.000000  313.0  11.5    5.0    4  2010    62       S
5    41.815126    NaN  14.3    5.0    5  2010    56       S
..         ...    ...   ...    ...  ...   ...   ...     ...
153  20.000000  223.0  11.5    9.0   30  2010    68       S
154  41.000000  190.0   7.4    5.0    1  2010    67       C
155  30.000000  193.0   6.9    9.0   26  2010    70      PS
156  41.815126  145.0  13.2    9.0   27  2010    77       S
158  18.000000  131.0   8.0    9.0   29  2010    76       C

[157 rows x 8 columns]

In [42]:
data['Weather'].value_counts().plot.bar()

Outlier Detection

In [43]:
#Histogram of Ozone
data_cleaned3['Ozone'].hist()

In [44]:
#Box_plot
data_box = data_cleaned3.dropna()
data1_box = data_box.Ozone
plt.boxplot(data1_box)

{'whiskers': [<matplotlib.lines.Line2D at 0x7ff3e652f8b0>,
 'caps': [<matplotlib.lines.Line2D at 0x7ff3e652ff40>,
 'boxes': [<matplotlib.lines.Line2D at 0x7ff3e652f6a0>],
 'medians': [<matplotlib.lines.Line2D at 0x7ff3e64b7490>],
 'fliers': [<matplotlib.lines.Line2D at 0x7ff3e64b7790>],
 'means': []}

In [45]:
dir(data_box)

['Day',
 'Month',
 'Ozone',
 'Solar',
 'T',
 'Temp',
 'Wind',
 'Year',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__r

In [46]:
#Extract Outliers
box = plt.boxplot(data['Ozone'].dropna())

In [47]:
type(box)
for i,j in box.items():
  print(i,j)

whiskers [<matplotlib.lines.Line2D object at 0x7ff3e64c6340>, <matplotlib.lines.Line2D object at 0x7ff3e64c6670>]
caps [<matplotlib.lines.Line2D object at 0x7ff3e64c69d0>, <matplotlib.lines.Line2D object at 0x7ff3e64c6d30>]
boxes [<matplotlib.lines.Line2D object at 0x7ff3e64c6190>]
medians [<matplotlib.lines.Line2D object at 0x7ff3e64c55e0>]
fliers [<matplotlib.lines.Line2D object at 0x7ff3e64c3e80>]
means []


In [48]:
#Fliers are outliers
[item.get_ydata() for item in box['fliers']]

[array([135., 168.])]

In [49]:
#To get whiskers
[item.get_ydata()[1] for item in box['whiskers']]

[1.0, 122.0]

In [50]:
#Descriptive  stst
data_cleaned3['Ozone'].describe()

count    157.000000
mean      41.815126
std       28.404353
min        1.000000
25%       21.000000
50%       41.815126
75%       45.000000
max      168.000000
Name: Ozone, dtype: float64

In [51]:
data_cleaned3

Ozone  Solar  Wind  Month  Day  Year  Temp
1    41.000000  190.0   7.4    5.0    1  2010    67
2    36.000000  118.0   8.0    5.0    2  2010    72
3    12.000000  149.0  12.6    5.0    3  2010    74
4    18.000000  313.0  11.5    5.0    4  2010    62
5    41.815126    NaN  14.3    5.0    5  2010    56
..         ...    ...   ...    ...  ...   ...   ...
153  20.000000  223.0  11.5    9.0   30  2010    68
154  41.000000  190.0   7.4    5.0    1  2010    67
155  30.000000  193.0   6.9    9.0   26  2010    70
156  41.815126  145.0  13.2    9.0   27  2010    77
158  18.000000  131.0   8.0    9.0   29  2010    76

[157 rows x 7 columns]

Scatter plot and Correlation Analysis

In [52]:
import seaborn as sns
#Create default pairplot
sns.pairplot(data_cleaned3)

In [53]:
data_cleaned3.corr()

Ozone     Solar      Wind     Month       Day  Year      Temp
Ozone  1.000000  0.308687 -0.520004  0.132860 -0.021916   NaN  0.606500
Solar  0.308687  1.000000 -0.057407 -0.094012 -0.155663   NaN  0.273558
Wind  -0.520004 -0.057407  1.000000 -0.166216  0.029900   NaN -0.441228
Month  0.132860 -0.094012 -0.166216  1.000000  0.050055   NaN  0.398516
Day   -0.021916 -0.155663  0.029900  0.050055  1.000000   NaN -0.122787
Year        NaN       NaN       NaN       NaN       NaN   NaN       NaN
Temp   0.606500  0.273558 -0.441228  0.398516 -0.122787   NaN  1.000000

Transformations

1) Dummy Variable

In [54]:
data_cleaned4

Ozone  Solar  Wind  Month  Day  Year  Temp Weather
1    41.000000  190.0   7.4    5.0    1  2010    67       S
2    36.000000  118.0   8.0    5.0    2  2010    72       C
3    12.000000  149.0  12.6    5.0    3  2010    74      PS
4    18.000000  313.0  11.5    5.0    4  2010    62       S
5    41.815126    NaN  14.3    5.0    5  2010    56       S
..         ...    ...   ...    ...  ...   ...   ...     ...
153  20.000000  223.0  11.5    9.0   30  2010    68       S
154  41.000000  190.0   7.4    5.0    1  2010    67       C
155  30.000000  193.0   6.9    9.0   26  2010    70      PS
156  41.815126  145.0  13.2    9.0   27  2010    77       S
158  18.000000  131.0   8.0    9.0   29  2010    76       C

[157 rows x 8 columns]

In [55]:
#Creating dummy variable for Weather column
data_cleaned = pd.get_dummies(data,columns = ['Weather'])

In [56]:
data_cleaned4

Ozone  Solar  Wind  Month  Day  Year  Temp Weather
1    41.000000  190.0   7.4    5.0    1  2010    67       S
2    36.000000  118.0   8.0    5.0    2  2010    72       C
3    12.000000  149.0  12.6    5.0    3  2010    74      PS
4    18.000000  313.0  11.5    5.0    4  2010    62       S
5    41.815126    NaN  14.3    5.0    5  2010    56       S
..         ...    ...   ...    ...  ...   ...   ...     ...
153  20.000000  223.0  11.5    9.0   30  2010    68       S
154  41.000000  190.0   7.4    5.0    1  2010    67       C
155  30.000000  193.0   6.9    9.0   26  2010    70      PS
156  41.815126  145.0  13.2    9.0   27  2010    77       S
158  18.000000  131.0   8.0    9.0   29  2010    76       C

[157 rows x 8 columns]

In [57]:
data_cleaned4 = data_cleaned.dropna()

Normalization of the data

In [58]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

In [59]:
data_cleaned4.values

array([[ 41. , 190. ,   7.4, ...,   0. ,   0. ,   1. ],
       [ 36. , 118. ,   8. , ...,   1. ,   0. ,   0. ],
       [ 12. , 149. ,  12.6, ...,   0. ,   1. ,   0. ],
       ...,
       [ 30. , 193. ,   6.9, ...,   0. ,   1. ,   0. ],
       [ 14. , 191. ,  14.3, ...,   0. ,   0. ,   1. ],
       [ 18. , 131. ,   8. , ...,   1. ,   0. ,   0. ]])

In [60]:
array = data_cleaned4.values

scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(array)

#transformed data
set_printoptions(precision=2)
print(rescaledX[0:5,:])

[[0.24 0.56 0.28 0.25 0.   0.   0.   0.25 0.   0.   1.  ]
 [0.21 0.34 0.31 0.38 0.   0.03 0.   0.38 1.   0.   0.  ]
 [0.07 0.43 0.56 0.43 0.   0.07 0.   0.43 0.   1.   0.  ]
 [0.1  0.94 0.5  0.12 0.   0.1  0.   0.12 0.   0.   1.  ]
 [0.13 0.89 0.34 0.2  0.   0.2  0.   0.2  0.   1.   0.  ]]


In [61]:
# Standardize data(0 mean, 1 stdev)
from sklearn.preprocessing import StandardScaler

In [62]:
array = data_cleaned4.values
scaler = StandardScaler().fit(array)
rescaledX = scaler.transform(array)

#Summarize transformed data
set_printoptions(precision=2)
print(rescaledX[0:5,:])

[[-0.02  0.05 -0.71 -1.15 -1.53 -1.7   0.   -1.15 -0.64 -0.68  1.28]
 [-0.17 -0.75 -0.54 -0.62 -1.53 -1.59  0.   -0.62  1.57 -0.68 -0.78]
 [-0.9  -0.41  0.77 -0.4  -1.53 -1.48  0.   -0.4  -0.64  1.47 -0.78]
 [-0.72  1.43  0.45 -1.69 -1.53 -1.36  0.   -1.69 -0.64 -0.68  1.28]
 [-0.57  1.27 -0.37 -1.37 -1.53 -1.02  0.   -1.37 -0.64  1.47 -0.78]]


Speed up the EDA process

In [63]:
!pip install pandas-profiling==3.1.0
!pip install sweetviz

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [64]:
import pandas_profiling as pp
import sweetviz as sv

In [65]:
EDA_report = pp.ProfileReport(data)
EDA_report.to_file(output_file='report2.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [66]:
sweet_report = sv.analyze(data)
sweet_report.show_html('weather_report.html')

                                             |          | [  0%]   00:00 -> (? left)

Report weather_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.
